# Permalinks
permalink:      /:year-:month-:day/:title

# Setup
title:          Eunhee Kim
baseurl:        ""
url:            https://euneestella.github.io/

# Assets
sass:
  sass_dir:     _sass
  style:        :compressed

# Build settings
markdown:       kramdown

# About
author:
  name:         Eunhee Kim
  url:          https://euneestella.github.io/
  email:        eunee.stella@gmail.com  
  github:       euneestella
  instagram:    eunee.stella

# Custom vars
version:        3.4.1
github:
  repo:         https://github.com/euneestella/euneestella.github.io
